//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public int BidId { get; set; }
        public int TournamentId { get; set; }
        public int TeamId { get; set; }
        public string Username { get; set; }
        public decimal Amount { get; set; }
        public string Other { get; set; }
    }
}
