//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESports.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBESportsEntities1 : DbContext
    {
        public DBESportsEntities1()
            : base("name=DBESportsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<TournamentDetail> TournamentDetails { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<PlayerReg> PlayerRegs { get; set; }
        public virtual DbSet<Bid> Bids { get; set; }
        public virtual DbSet<Auction> Auctions { get; set; }
    }
}
