//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string Username { get; set; }
        public string Batting { get; set; }
        public string Bowling { get; set; }
        public string Other { get; set; }
        public string Photo { get; set; }
    }
}
